"""empty message

Revision ID: fa111abbf9cc
Revises: 6fbaf657f67e
Create Date: 2022-04-20 18:03:46.473457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa111abbf9cc'
down_revision = '6fbaf657f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
